sonar.projectKey=chshiv_AC_price_prediction_system

sonar.organization=chshiv


sonar.projectName=AC Price Prediction System


sonar.sources=backend,frontend/src


sonar.exclusions=**

frontend/node_modules/**,
backend/__pycache__/**,
**/*.pkl,
**/*.xls


sonar.python.version=3.11